"""
t2t — TOML to Tailwind CSS theme converter.

Entry point and top-level orchestration. Parses CLI arguments, loads the TOML
file, delegates to the module layer, and writes the CSS output.

Module responsibilities:

```
color.py      — oklch parsing, formatting, color_ramp()
gamut.py      — oklch → linear sRGB conversion, sRGB gamut validation
dsl.py        — ramp() DSL string resolver
contrast.py   — WCAG contrast ratio + [[contrast]] validation
typography.py — line-height and letter-spacing derivation from font-size
palette.py    — palette step generation and palette map construction
tokens.py     — [[token]] light/dark resolution
render.py     — CSS section renderers
output.py     — stderr summary table
```
"""

import argparse
import subprocess
import sys
import tomllib
from pathlib import Path

import csscompressor

from .contrast import validate_contrast
from .output import build_report, print_summary
from .palette import build_palette_map
from .render import (
    render_base,
    render_components,
    render_dark,
    render_root,
    render_static,
    render_text_utilities,
    render_theme,
    render_tint_utilities,
    render_utilities,
)
from .tokens import build_comments_map, build_token_maps


def convert(data: dict) -> tuple[str, dict[str, str], dict[str, str]]:
    """
    Convert a parsed TOML theme dict into a CSS string.

    Runs gamut validation on all computed colors as a side-effect.

    Args:
        data: Parsed TOML dict (from tomllib.load).

    Returns:
        (css, light_map, dark_map) where light_map and dark_map are the
        resolved [[token]] color maps, needed for contrast validation and
        the summary table.
    """
    palette_map         = build_palette_map(data.get("palette", []))
    light_map, dark_map = build_token_maps(data.get("token", []), palette_map)
    comments_map        = build_comments_map(data.get("token", []))

    sections = [
        render_base(data.get("font", [])),
        render_theme(data.get("palette", [])),
        render_utilities(
            data.get("font", []),
            data.get("typography", {}),
            data.get("utilities", {}),
        ),
        render_components(data.get("components", {})),
        render_root(data.get("root", {}), palette_map, light_map, dark_map, comments_map),
        render_dark(dark_map),
        render_static(data.get("static", {})),
    ]
    css = "\n\n\n".join(s for s in sections if s) + "\n"
    return css, light_map, dark_map


def convert_split(data: dict) -> dict[str, str]:
    """
    Convert a parsed TOML theme dict into four separate CSS files.

    Returns a dict with keys:

    ```
    theme       — :root tokens + dark toggle + static (color-scheme) rules
    typography  — @utility blocks from [text] (display, title, body, …)
    utilities   — @utility tint-* + font utilities + custom [utilities]
    wimwian     — @import manifest (tailwindcss + the three above)
    ```

    Unlike convert(), gamut validation is still run as a side-effect via
    build_token_maps. Contrast validation must be called separately.
    """
    meta = data.get("meta", {})
    pkg_name    = meta.get("name", "theme")
    pkg_version = meta.get("version", "")

    palette_map   = build_palette_map(data.get("palette", []))
    palette_names = [p["name"] for p in data.get("palette", [])]
    tokens        = data.get("token", [])
    light_map, dark_map = build_token_maps(tokens, palette_map)
    comments_map  = build_comments_map(tokens)

    # ── theme.css ─────────────────────────────────────────────────────────────
    theme_parts = [
        render_base(data.get("font", [])),
        render_root(data.get("root", {}), palette_map, light_map, dark_map, comments_map),
        render_dark(dark_map),
        render_static(data.get("static", {})),
    ]
    theme_css = "\n\n\n".join(p for p in theme_parts if p) + "\n"

    # ── typography.css ────────────────────────────────────────────────────────
    typography_css = render_text_utilities(data.get("text", {})) + "\n"

    # ── utilities.css ─────────────────────────────────────────────────────────
    util_parts = [
        render_tint_utilities(palette_names, tokens),
        render_utilities(data.get("font", []), {}, data.get("utilities", {})),
        render_components(data.get("components", {})),
    ]
    utilities_css = "\n\n\n".join(p for p in util_parts if p) + "\n"

    # ── wimwian.css ───────────────────────────────────────────────────────────
    ver = f" v{pkg_version}" if pkg_version else ""
    lines = [
        f"/* {pkg_name}{ver} — generated by t2t */",
        '@import "tailwindcss";',
        '@import "./theme.css";',
    ]
    if typography_css.strip():
        lines.append('@import "./typography.css";')
    if utilities_css.strip():
        lines.append('@import "./utilities.css";')
    wimwian_css = "\n".join(lines) + "\n"

    return {
        "theme":      theme_css,
        "typography": typography_css,
        "utilities":  utilities_css,
        "wimwian":    wimwian_css,
    }


def _build_minified(css_files: dict[str, str]) -> str:
    """
    Return a single consolidated, minified CSS string.

    Concatenates theme, typography, and utilities sections and compresses them
    with csscompressor. Prepends a bare @import "tailwindcss"; so the output
    has no other file dependencies.
    """
    combined = "\n".join(
        css_files[k] for k in ("theme", "typography", "utilities")
        if css_files[k].strip()
    )
    return '@import "tailwindcss";' + csscompressor.compress(combined)


def _prettier(paths: list[Path]) -> None:  # pragma: no cover
    """Run prettier --write via npx; warns and continues if npx is absent."""
    try:
        subprocess.run(
            ["npx", "--yes", "prettier", "--write", *[str(p) for p in paths]],
            check=True,
            capture_output=True,
        )
    except FileNotFoundError:
        print("t2t: warning: npx not found, skipping prettier", file=sys.stderr)
    except subprocess.CalledProcessError as e:
        print(f"t2t: warning: prettier failed\n{e.stderr.decode()}", file=sys.stderr)


def main() -> None:  # pragma: no cover
    parser = argparse.ArgumentParser(
        prog="t2t",
        description="Convert a TOML theme configuration into a Tailwind-compatible CSS file.",
    )
    parser.add_argument("-i", "--input",  required=True, help="Input TOML file")
    parser.add_argument("-o", "--output", help="Output CSS file (default: stdout)")
    parser.add_argument("-d", "--dryrun", action="store_true", help="Print output without writing")
    parser.add_argument("-m", "--add-minified", action="store_true",
                        help="Also write a minified copy alongside the output (output-min.css)")
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"t2t: error: input file not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    with open(input_path, "rb") as f:
        data = tomllib.load(f)

    css_files = convert_split(data)

    palette_map          = build_palette_map(data.get("palette", []))
    tokens               = data.get("token", [])
    light_map, dark_map  = build_token_maps(tokens, palette_map)
    warnings             = validate_contrast(data.get("contrast", []), palette_map, light_map, dark_map)
    print_summary(data, palette_map, light_map, dark_map, warnings)

    if args.dryrun or not args.output:
        for name, content in css_files.items():
            if content.strip():
                print(f"\n/* ── {name}.css ── */\n{content}")
    else:
        out = Path(args.output)
        theme_path    = out.parent / "theme.css"
        typo_path     = out.parent / "typography.css"
        util_path     = out.parent / "utilities.css"
        out.write_text(css_files["wimwian"])
        theme_path.write_text(css_files["theme"])
        typo_path.write_text(css_files["typography"])
        util_path.write_text(css_files["utilities"])
        (out.parent / "report.md").write_text(build_report(data, palette_map, light_map, dark_map))
        _prettier([out, theme_path, typo_path, util_path])
        if args.add_minified:
            min_path = out.with_stem(out.stem + "-min")
            min_path.write_text(_build_minified(css_files))


if __name__ == "__main__":  # pragma: no cover
    main()
